// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0VF6ywCeAB8TClgV1VRJeiroFYPHpIK8',
    appId: '1:400076438283:web:7c24fe4269616e4f89000e',
    messagingSenderId: '400076438283',
    projectId: 'personal-task-manager-8d137',
    authDomain: 'personal-task-manager-8d137.firebaseapp.com',
    storageBucket: 'personal-task-manager-8d137.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF8PyAtBmnj0_H0s38BnBGwghbI9mGPgM',
    appId: '1:400076438283:android:146d9a9d80e4861389000e',
    messagingSenderId: '400076438283',
    projectId: 'personal-task-manager-8d137',
    storageBucket: 'personal-task-manager-8d137.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYsCYkkZhTV8nSlBD48t-zXWWjFEwHdgU',
    appId: '1:400076438283:ios:3367de220b9b362a89000e',
    messagingSenderId: '400076438283',
    projectId: 'personal-task-manager-8d137',
    storageBucket: 'personal-task-manager-8d137.firebasestorage.app',
    iosBundleId: 'com.example.personalTaskManager',
  );
}
